version: "3"

services:
  frontend:
    image: node:18
    container_name: node-base-app
    command: npm run dev --expose
    working_dir: /usr/app/frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/usr/app/frontend:delegated

  backend:
    image: cyberduck/php-fpm-laravel:8.2
    container_name: php-base-app
    working_dir: /usr/app/backend
    ports:
      - 9000:9000
    volumes:
      - ./backend:/usr/app/backend:delegated

  composer:
    image: cyberduck/php-fpm-laravel:8.2
    container_name: composer
    volumes:
      - ./backend:/usr/app/backend
    working_dir: /usr/app/backend
    depends_on:
      - backend
    entrypoint: ["composer"]

  npmb:
    image: node:18
    container_name: npm
    volumes:
      - ./backend:/usr/app/backend
    working_dir: /usr/app/backend
    entrypoint: ["npm"]

  npmf:
    image: node:18
    container_name: npm
    volumes:
      - ./frontend:/usr/app/frontend
    working_dir: /usr/app/frontend
    entrypoint: ["npm"]

  artisan:
    image: cyberduck/php-fpm-laravel:8.2
    container_name: artisan
    volumes:
      - ./backend:/usr/app:delegated
    working_dir: /usr/app
    entrypoint: ["php", "/usr/app/backend/artisan"]
